cndi_version: v1
project_name: my-cndi-project
deployment_target_provider: aws
deployment_target_distribution: microk8s
infrastructure:
  cndi:
    cert_manager:
      email: jane.doe@example.com
    node_groups:
      - name: basic-nodes # basic-nodes-0 is the leader
        count: 3 # min and max are not available in microk8s leader_count=1 + count_follower=2
        instance_type: t3.2xlarge

      - name: gpu-nodes
        # role: controller
        volume_size: 128
        # min: 3
        # max: 5
        # or
        count: 3 # 3
        instance_type: g4dn.xlarge


        # worker: true
        # min:
        # max:
        # role: worker
        # instance_type: t3.2xlarge
        # auxiliary_disk: 128Gi
        # 