cndi_version: v2
project_name: mj-ec2-airflow
provider: dev # local but single-node and easy to iterate | 'baremetal' | 'aws'
distribution: microk8s # 'rke2'
infrastructure:
  cndi:
    open_ports:
      - name: kubeapi
        number: 16443
    cert_manager:
      email: matt.johnston@polyseam.io
    nodes:
      - name: airflow-alpha
        instance_type: t3.medium
        disk_size: 100
      - name: airflow-beta
        instance_type: t3.medium
        disk_size: 100
cluster_manifests: {}
applications: {}