cndi_version: v2
project_name: basic-cluster
provider: aws # or 'gcp', 'azure'
distribution: eks # or 'clusterless'
infrastructure:
  cndi:
    network:
      mode: # 'insert' # or 'create'
      vpc_id: hub-vpc-123
      prefix: # defaults to '10.0.0.0/20'
    #     private: false

    cert_manager:
      email: matt.johnston@polyseam.io
    nodes:
      - name: airflow-alpha
        instance_type: t3.medium # or 'n1-standard-2', 'Standard_D2_v2'
        disk_size: 100

cluster_manifests: {}
applications: {}
