on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
env: # this is a Read-Only token for Public Repositories see: https://github.com/polyseam/cndi/pull/863
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  CNDI_TELEMETRY: "none"
jobs:
  bin-build-test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.1.4"
      - name: deno build-linux
        run: deno task build-linux
      - name: linux cndi --help
        run: ./dist/linux/in/cndi --help
        timeout-minutes: 1

  bin-build-test-macos-amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.1.4"
      - name: deno build-mac-amd64
        run: deno task build-mac-amd64
      - name: mac cndi --help
        run: ./dist/mac-amd64/in/cndi --help
        timeout-minutes: 1

  bin-build-test-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.1.4"
      - name: deno build-mac-arm64
        run: deno task build-mac-arm64
      - name: mac cndi --help
        run: ./dist/mac-arm64/in/cndi --help
        timeout-minutes: 1

  bin-build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.1.4"
      - name: deno build-win
        run: deno task build-win
      - name: win cndi --help
        run: ./dist/win/in/cndi.exe --help
        timeout-minutes: 1
