name: Build and Release for GitHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.1.9"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version from deno.json
        uses: polyseam/get-version-key-from-json@v1.0.0
        id: get_deno_json
        with:
          path-to-json: "./deno.json"

      - name: Get the tag version without prefix
        id: get_version_from_ref
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Compare Git Tag to CNDI Version
        if: ${{ steps.get_deno_json.outputs.version != steps.get_version_from_ref.outputs.VERSION }}
        run: |
          echo "CNDI Version: ${{ steps.get_deno_json.outputs.version }} does not match Tag version: ${{ steps.get_version_from_ref.outputs.VERSION }}" && exit 1

      - name: Build
        run: deno task build

      # this ensures `cndi upgrade` works for users with cndi@<v2.27
      # it's a waste of disk space for GitHub and we should remove it when we are certain all users have upgraded
      - name: duplicate macos archive for backwards compatibility
        # assumes the user will be on apple silicon despite the previous macos version being amd64
        run: cp ./dist/release-archives/cndi-mac-arm64.tar.gz ./dist/release-archives/cndi-mac.tar.gz

      - name: duplicate linux archive for backwards compatibility
        run: cp ./dist/release-archives/cndi-linux-amd64.tar.gz ./dist/release-archives/cndi-linux.tar.gz

      - name: duplicate windows archive for backwards compatibility
        run: cp ./dist/release-archives/cndi-win-amd64.tar.gz ./dist/release-archives/cndi-win.tar.gz

      - name: Install cndi dependency binaries
        run: mkdir -p /home/runner/.cndi/bin && cp ./dist/linux-amd64/in/* /home/runner/.cndi/bin

      - name: Test
        run: deno task test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            dist/release-archives/cndi-*
