on:
  pull_request:
    branches:
      - main
jobs:
  test_and_lint: # cndi
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.2

      - run: deno task checks

      - name: Install cndi dependency binaries
        run: mkdir -p /home/runner/.cndi/bin && cp ./dist/linux-amd64/in/* /home/runner/.cndi/bin

      - run: deno task test
