name: main # used by the cndi team, not end users
on:
  push:
    branches:
      - "main"
jobs:
  main-test-and-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.2

      - run: deno task checks

      - name: Install cndi dependency binaries
        run: mkdir -p /home/runner/.cndi/bin && cp ./dist/linux-amd64/in/* /home/runner/.cndi/bin

      - run: deno task test

  main-build: # cndi
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.2

      - run: deno task build

      - id: upload-source-code
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "cndi-binaries"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "./dist/release-archives"
          DEST_DIR: "cndi/main"
