on:
  pull_request:
    branches:
      - main
jobs:
  test_and_lint: # cndi
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.2

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Type check
        run: deno task check

      - name: Install cndi dependency binaries
        run: mkdir -p /home/runner/.cndi/bin && cp ./dist/linux-amd64/in/* /home/runner/.cndi/bin

      - name: Test
        run: deno task test
